rocketmq:
  producer:
    group: product
swagger:
  title: SellerProduct
  description: 卖家商品管理
  exclude-path:
    - /actuator/**
    - /error
  apply-default-response-messages: false
  global-response-message:
    get: