
mybatis:
  mapper-locations: classpath:com/yuyuko/mall/user/dao/xml/*.xml
  configuration:
    map-underscore-to-camel-case: true
rocketmq:
  producer:
    group: user
swagger:
  title: User
  description: 用户信息管理
  exclude-path:
    - /actuator/**
    - /error
  apply-default-response-messages: false
  global-response-message:
    get: