dubbo:
  protocol:
    name: dubbo
    port: -1
  consumer:
    check: false
  registry:
    address: spring-cloud://localhost
    check: false
  cloud:
    subscribed-services: shop,stock
  scan:
    base-packages: com.yuyuko.mall.product.api.impl